def yes?(question)
  answer = ask "     \e[1m\e[32mpromp".rjust(10) + "  \e[0m#{question} \e[33m(y/n)\e[0m"
  case answer.downcase
  when 'yes', 'y'
    true
  when 'no', 'n'
    false
  else
    yes?(question)
  end
end

def prompt(question, options)
  answer = ask("     \e[1m\e[32mpromp".rjust(10) + "  \e[0m#{question} \e[33m[#{options[:default_answer]}]\e[0m").strip
  answer.present? ? answer : options[:default_answer]
end

def rewrite_file(file_name, content)
  system "rm #{file_name} && > #{file_name}"
  append_to_file(file_name, content)
end

def database_adapter
  case @database
  when 'postgresql', 'postgres', 'psql' then 'pg'
  when 'mysql'                          then 'mysql2'
  when 'sqlite'                         then 'sqlite3'
  else @database
  end
end


@database = prompt 'What database you want to use?', default_answer: 'postgresql'
@create_commits = true if yes?('Create first git commits?')

remove_file 'public/index.html'
remove_file 'app/assets/images/rails.png'

rewrite_file 'Gemfile', %Q(
source 'https://rubygems.org'
ruby '1.9.3'

gem 'haml-rails'
gem 'jquery-rails'
gem '#{database_adapter}'
gem 'rails', '3.2.9'

group :development do
  gem 'thin'
end

group :development, :test do
  gem 'pry'
  gem 'awesome_print'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'forgery'
  gem 'poltergeist'
  gem 'rspec-rails'
  gem 'simplecov', require: false
end

group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
).strip

rewrite_file '.gitignore', %Q(
# See http://help.github.com/ignore-files/ for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile ~/.gitignore_global

# Ignore bundler config
/.bundle

# Ignore all logfiles and tempfiles
/log/*.log
/tmp

# Ignore config files
/config/database.yml

# Ignore docs
/doc/api
/doc/app

# Ignore public sub-directories
/public/packages/*
/public/system/*

# Ignore files from text editors and IDEs
Session.vim
*.sw?

# Ignore files from Operating System
*~
.DS_Store

# Ignore files from Ctags
/tags

# Ignore files from RVM
/.rvmrc

# Ignore files from SASS
/.sass-cache/

# Ignore routes cache
/.routes

# Ignore simplecov files
coverage/

# Ignore other files
rails_best_practices_output.html
).strip

system 'bundle install'

if @create_commits
  system 'git init'
  system 'git add .'
  system "git commit -am 'Initial Rails directory structure'"
end

# if yes?('Install and configure Twitter Bootstrap Rails gem?')
# end
#
# if yes?('Install and configure Devise gem?')
# end

if yes?('Use brazilian portuguese locale (I18n)?')
  remove_file 'config/locales/en.yml'
  # Include config/locales*.pt-BR.yml files
  # Update config/application.rb
end
